spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:host}
      port: ${MONGODB_PORT:2701}
      username: ${MONGODB_USERNAME:user}
      password: ${MONGODB_PASSWORD:password}
      database: ${MONGODB_DATABASE_NAME:smart-charging}
