spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:username}
      password: ${MONGODB_PASSWORD:password}
      database: ${MONGODB_DATABASE_NAME:workSchedule}
      authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
